using TqkLibrary.VpnClient.ZeroTier.Identity;
using Xunit;

namespace TqkLibrary.VpnClient.ZeroTier.Tests
{
    /// <summary>
    /// Golden known-answer tests for the memory-hard address derivation, using real identities generated by
    /// <c>zerotier-idtool generate</c> (V.7.3 live lab). Each vector is <c>(address, publicKeyHex)</c> straight from
    /// the idtool identity string <c>&lt;address&gt;:0:&lt;publicKey128hex&gt;:&lt;private...&gt;</c>. The address is
    /// public data (no secret committed), so these vectors are safe to hardcode and lock interop for good.
    /// </summary>
    public class ZeroTierAddressKatTests
    {
        readonly ZeroTierAddressDerivation _derive = new ZeroTierAddressDerivation();

        static byte[] FromHex(string hex)
        {
            byte[] b = new byte[hex.Length / 2];
            for (int i = 0; i < b.Length; i++) b[i] = Convert.ToByte(hex.Substring(i * 2, 2), 16);
            return b;
        }

        [Theory]
        // address      publicKeyHex (128 hex = 64 bytes: Curve25519 || Ed25519) — from `zerotier-idtool generate`
        [InlineData("51e9af2da9", "aab1e9e9f535189cbab010b14c1cc7edf239a0cc9e3a780dc931b9f59c824863a6937ca51fb6e9595762e52f18c82c94b8d8be130699a810094c9c16d7249b93")]
        [InlineData("03ebdd1acc", "aab0e477c1e75236e49a226e9e50ca17795d1b5b2cca8c337a6db3501cbcd458b8b100d939555bd77f98d705c4985b9d27d7816ed6485330d45961fdef7045f9")]
        [InlineData("5ea424f73e", "1cadcff08bf215736dc151545d4ce8a98dafd4a11353188c28b708e17524af46f1cb03e7adee56712d56957852ed7d0d402cb63468c450af021b3e2549d3ec38")]
        [InlineData("177bde409b", "99ed2c5f8d740e1447dc1859bcdd1652b9fadfa9d19db13e54a3986bf7ae7476cccd3eb1a662b53169592c0b046b5ad621fee102e196144ca913c3c512add57b")]
        [InlineData("b46ca134ec", "9f17260755d636e634963f77801fd4c952ef7710431bb7a6d33ade484c53342cf21dfd29d99cab1ed485b6be78f300c1789fa1a3ad8e5545935d73ce36243ac8")]
        [InlineData("0087ab6db7", "5cc75af2ae0f9e98fc95d36defeb54009b77de2735ff6086fc00991263802b7d894af14c9b437aeafb9adb270adceea78a2f483592c94a11d89f3412cd19fd90")]
        [InlineData("c2af357fac", "7d095279a9d99dd726cfb438791d553a0c2aefef9197baa1861fc6d076ac331422eb056a03b81702b2680a46fc5c193af2e8aafe38bfe1d90905dffd52574152")]
        [InlineData("06560be276", "df6d62a3cf65db597d43113ce3e647160e8df2d79e334c4ffc30b726255427301226a9883c1540aa629bf174ad36cd3627566aacf75f603dd4eba68ba5ae0f5d")]
        public void ComputeAddress_MatchesIdtool(string expectedAddress, string publicKeyHex)
        {
            byte[] pub = FromHex(publicKeyHex);
            bool pow = _derive.TryComputeDigest(pub, out _, out var address);

            Assert.Equal(expectedAddress, address.ToString());
            // A real idtool identity always satisfies the proof-of-work gate (digest[0] < 17).
            Assert.True(pow, "idtool identities must satisfy the hashcash proof-of-work");
        }
    }
}
