using System;
using System.Security.Cryptography;

namespace TqkLibrary.VpnClient.Drivers.Tailscale.Config
{
    /// <summary>
    /// The static configuration to log a node into a Tailscale-compatible coordination server (Headscale or
    /// <c>login.tailscale.com</c>) and bring a WireGuard tunnel up from the resulting netmap. Tailscale's node key is
    /// the WireGuard key, so this config holds two 32-byte X25519 private keys the client owns: the
    /// <see cref="MachinePrivateKey"/> (the ts2021 Noise control static) and the <see cref="NodePrivateKey"/> (the
    /// WireGuard / data-plane key). Both are generated by <see cref="Generate"/> when not supplied.
    /// <para>
    /// The data plane is reused wholesale from WireGuard; this config carries only the control-plane inputs (server URL,
    /// preauth key, keys, hostname, MTU). DERP relaying and disco NAT traversal are future work, so peers must be
    /// directly reachable in the lab.
    /// </para>
    /// </summary>
    public sealed class TailscaleConfig
    {
        /// <summary>The coordination server base URL (e.g. <c>http://headscale:8080</c>). Required.</summary>
        public required Uri ServerUrl { get; init; }

        /// <summary>The preauthentication key (Headscale <c>preauthkeys create</c>) authorizing this node. Required.</summary>
        public required string PreauthKey { get; init; }

        /// <summary>This client's 32-byte X25519 machine private key (the ts2021 Noise control static). Required.</summary>
        public required byte[] MachinePrivateKey { get; init; }

        /// <summary>This client's 32-byte X25519 node private key — the WireGuard data-plane private key. Required.</summary>
        public required byte[] NodePrivateKey { get; init; }

        /// <summary>The hostname reported to the control server in <c>Hostinfo</c>; defaults to a generic name when null.</summary>
        public string? Hostname { get; init; }

        /// <summary>The tunnel MTU; defaults to 1280 (Tailscale's default).</summary>
        public int Mtu { get; init; } = 1280;

        /// <summary>
        /// Generates a config with fresh random machine and node keys. <paramref name="serverUrl"/> and
        /// <paramref name="preauthKey"/> are required; the rest take defaults. Use this for a first-time login where the
        /// node has no persisted keys.
        /// </summary>
        public static TailscaleConfig Generate(Uri serverUrl, string preauthKey, string? hostname = null, int mtu = 1280)
        {
            return new TailscaleConfig
            {
                ServerUrl = serverUrl,
                PreauthKey = preauthKey,
                MachinePrivateKey = NewX25519PrivateKey(),
                NodePrivateKey = NewX25519PrivateKey(),
                Hostname = hostname,
                Mtu = mtu,
            };
        }

        static byte[] NewX25519PrivateKey()
        {
            // X25519 clamps internally, so any 32 random bytes form a valid private key (same as Curve25519DhGroup).
            byte[] key = new byte[32];
            using var rng = RandomNumberGenerator.Create();
            rng.GetBytes(key);
            return key;
        }
    }
}
